server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: NEFU
    url: jdbc:mysql://test.ricemarch.com:3306/cms_user?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
  jackson:
    default-property-inclusion: non_null



logging:
  level:
    root: warn
    com.ricemarch: debug
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'

# mybatis-plus start #
mybatis-plus:
  configuration:
    cache-enabled: false
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-column-underline: true
    field-strategy: 2
    id-type: 2
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

# mybatis-plus end #